### ISSUE TITLE
Final purpose of this project

### ISSUE THREAD

**Issue by Magissia** [mattn/sudo#11]
Is the point of this project to create a full sudo like in linux, or juste to force an UAC prompt from a terminal for arbitrary commands ? (like [elevate.exe](https://www.winability.com/info/elevate/) ?)

**Comment by mattn** [comment]
Implementation of the sudo command with some compatibility is possible but not portable since it needs to be installed as an NT service or use a task scheduler to elevate without UAC prompt. This project provide as much interface as possible to the genuine sudo command. Please check feature of sudo.exe your self. (or read code)
